#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🎨 Formatting and linting staged files..."
npx lint-staged

if [ $? -ne 0 ]; then
  echo "❌ Formatting or linting failed! Commit aborted."
  exit 1
fi

echo "✅ Files formatted and linted successfully!"
